version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: moneybeing_db
    environment:
      POSTGRES_DB: loan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: moneybeing_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/loan_db
      JWT_SECRET: super_secret_jwt_key_moneybeing_2026_assessment
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: moneybeing_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  pgdata:
